services:
  postgres:
    image: postgres:17.0
    restart: always
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic

  # http://localhost:23000/
  grafana:
    build: './monitoring/config/grafana'
    container_name: grafana
    ports:
      - "23000:3000"
    restart: always
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # http://localhost:29090/
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "29090:9090"
    restart: always
    volumes:
      - ./monitoring/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
