services:
  petclinic:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: petclinic
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://petclinic-db:5432/petclinic
      - SPRING_APPLICATION_NAME=petclinic
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=10
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
    volumes:
      - ./jfr/petclinic:/jfr
    tty: true

  petclinic-aot:
    build:
      dockerfile: DockerfileAOT
      context: .
    container_name: petclinic-aot
    ports:
      - "8091:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://petclinic-db:5432/petclinicaot
      - SPRING_APPLICATION_NAME=petclinic-aot
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=10
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
    volumes:
      - ./jfr/petclinic-aot:/jfr
    tty: true

  petclinic-cds:
    build:
      dockerfile: DockerfileCDS
      context: .
    container_name: petclinic-cds
    ports:
      - "8092:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://petclinic-db:5432/petcliniccds
      - SPRING_APPLICATION_NAME=petclinic-cds
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=10
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
    volumes:
      - ./jfr/petclinic-cds:/jfr
    tty: true

  petclinic-crac:
    build:
      dockerfile: DockerfileCRaC
      context: .
    container_name: petclinic-crac
    ports:
      - "8093:8080"
    environment:
      - SPRING_APPLICATION_NAME=petclinic-crac
      - CRAC_RESTORE
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=10
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
    tty: true
    cap_add:
      - CHECKPOINT_RESTORE
      - SYS_PTRACE
    volumes:
      - ./crac-files:/app/crac-files
      - ./jfr/petclinic-crac:/jfr
    command: >
      sh -c "
      if [ \"$CRAC_RESTORE\" = \"true\" ]; then
        java -XX:CRaCRestoreFrom=/app/crac-files;
      else
        java -XX:CRaCCheckpointTo=/app/crac-files -jar spring-petclinic.jar;
      fi
      "

  petclinic-native:
    build:
      dockerfile: DockerfileNative
      context: .
    container_name: petclinic-native
    ports:
      - "8094:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://petclinic-db:5432/petclinicnative
      - SPRING_APPLICATION_NAME=petclinic-native
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=10
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
    volumes:
      - ./jfr/petclinic-native:/jfr
    tty: true

  petclinic-db:
    build:
      dockerfile: ./Dockerfile
      context: postgres
    container_name: petclinic-db
    ports:
      - "35432:5432"
    volumes:
      - petclinic_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  # http://localhost:23000/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "23000:3000"
    volumes:
      - ./monitoring/config/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  # http://localhost:24040/
  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    ports:
      - "24040:4040"
    command: server
    environment:
      - PYROSCOPE_LOG_LEVEL=debug

  # http://localhost:29090/
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "29090:9090"
    volumes:
      - ./monitoring/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  petclinic_data:
