{
 "title": "Comparison of Spring Boot optimizations",
 "description": "Comparison of Spring Boot optimizations",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"petclinic\"}",
     "legendFormat": "petclinic"
    },
    {
     "expr": "process_cpu_usage{application=\"petclinic-aot\"}",
     "legendFormat": "petclinic-aot"
    },
    {
     "expr": "process_cpu_usage{application=\"petclinic-cds\"}",
     "legendFormat": "petclinic-cds"
    },
    {
     "expr": "process_cpu_usage{application=\"petclinic-crac\"}",
     "legendFormat": "petclinic-crac"
    },
    {
     "expr": "process_cpu_usage{application=\"petclinic-native\"}",
     "legendFormat": "petclinic-native"
    },
    {
     "expr": "process_cpu_usage{application=\"petclinic-local\"}",
     "legendFormat": "petclinic-local"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"petclinic\"})",
     "legendFormat": "petclinc"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"petclinic-aot\"})",
     "legendFormat": "petclinc-aot"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"petclinic-cds\"})",
     "legendFormat": "petclinc-cds"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"petclinic-crac\"})",
     "legendFormat": "petclinc-crac"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"petclinic-native\"})",
     "legendFormat": "petclinc-native"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"petclinic-local\"})",
     "legendFormat": "petclinic-local"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"petclinic\"}[10s]))",
     "legendFormat": "petclinic"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"petclinic-aot\"}[10s]))",
     "legendFormat": "petclinic-aot"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"petclinic-cds\"}[10s]))",
     "legendFormat": "petclinic-cds"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"petclinic-crac\"}[10s]))",
     "legendFormat": "petclinic-crac"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"petclinic-native\"}[10s]))",
     "legendFormat": "petclinic-native"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"petclinic-local\"}[10s]))",
     "legendFormat": "petclinic-local"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"petclinic\", status!~\"5..\"}[10s]))/sum(rate(http_server_requests_seconds_count{application=\"petclinic\", status!~\"5..\"}[10s]))",
     "legendFormat": "petclinic"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"petclinic-aot\", status!~\"5..\"}[10s]))/sum(rate(http_server_requests_seconds_count{application=\"petclinic-aot\", status!~\"5..\"}[10s]))",
     "legendFormat": "petclinic-aot"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"petclinic-cds\", status!~\"5..\"}[10s]))/sum(rate(http_server_requests_seconds_count{application=\"petclinic-cds\", status!~\"5..\"}[10s]))",
     "legendFormat": "petclinic-cds"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"petclinic-crac\", status!~\"5..\"}[10s]))/sum(rate(http_server_requests_seconds_count{application=\"petclinic-crac\", status!~\"5..\"}[10s]))",
     "legendFormat": "petclinic-crac"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"petclinic-native\", status!~\"5..\"}[10s]))/sum(rate(http_server_requests_seconds_count{application=\"petclinic-native\", status!~\"5..\"}[10s]))",
     "legendFormat": "petclinic-native"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"petclinic-local\", status!~\"5..\"}[10s]))/sum(rate(http_server_requests_seconds_count{application=\"petclinic-local\", status!~\"5..\"}[10s]))",
     "legendFormat": "petclinic-local"
    }
   ]
  },
  {
   "title": "Ready Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{application=\"petclinic\"}",
     "legendFormat": "petclinic"
    },
    {
     "expr": "application_ready_time_seconds{application=\"petclinic-aot\"}",
     "legendFormat": "petclinic-aot"
    },
    {
     "expr": "application_ready_time_seconds{application=\"petclinic-cds\"}",
     "legendFormat": "petclinic-cds"
    },
    {
     "expr": "application_ready_time_seconds{application=\"petclinic-crac\"}",
     "legendFormat": "petclinic-crac"
    },
    {
     "expr": "application_ready_time_seconds{application=\"petclinic-native\"}",
     "legendFormat": "petclinic-native"
    },
    {
     "expr": "application_ready_time_seconds{application=\"petclinic-local\"}",
     "legendFormat": "petclinic-local"
    }
   ]
  }
 ]
}