scrape_configs:
  - job_name: 'petclinic'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['petclinic:8081']
  - job_name: 'petclinic-aot'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['petclinic-aot:8081']
  - job_name: 'petclinic-cds'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['petclinic-cds:8081']
  - job_name: 'petclinic-crac'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['petclinic-crac:8081']
